# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package
      #- run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: target/*.jar
          #path: staging
      #Run *.bat file
      #- name: Run *.bat file install
      #   run: C:\KafkaData\CIRunner.bat

      #- name: go to installed file
      #  run: cd D:\temp

      #- name: start application
      #  run: java -jar test-1.0-SNAPSHOT.jar > D:\temp\test.log

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
  
  test: 
    if: github.event_name == 'pull_request' && github.base_ref == 'test'
    #pull_request:
    #  branches: [ test ]
    needs: build
    runs-on: self-hosted
    steps: 
      # 部署
      - name: test start deployment project
        run: ./deployment.bat
      # 启动项目和测试
      - name: start test
        run: ./runlistener.bat
      # 回传数据
      #- name: upload test result data
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: TestResult
      #    path: target/*.txt
